[WIP][menu] Add way to register menu items #106
openwisp/openwisp-utils pull request #152
Opened 2020-10-25 09:22 UTC by atb00ker

Closes #106

2020-10-25 09:25 UTC, TravisBuddy commented
## Travis tests have failed

Hey @atb00ker,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 6th Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;openwisp&#x2F;openwisp-utils&#x2F;jobs&#x2F;738689986">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;run-qa-checks
    </strong>
  </summary>

```
SUCCESS: Blank endline check successful!
SUCCESS: Migration name check on "./tests/test_project/migrations" with migrations-to-ignore: 0 successful!
Skipped 1 files
SUCCESS: Isort check successful!
All done! ✨ 🍰 ✨
47 files would be left unchanged.
SUCCESS: Black check successful!
./tests/test_project/apps.py:1:1: F401 'django.conf.settings' imported but unused
ERROR: Flake8 check failed!
SUCCESS: ReStructuredText check successful!
SUCCESS: Commit message check successful!
No changes detected
SUCCESS: Migrations check successful!
```

</details>


###### TravisBuddy Request Identifier: 0a269380-16a4-11eb-a761-09290313622d

2020-10-26 16:04 UTC, nemesisdesign requested changes
Thanks Ajay! See my comments below.

2020-10-26 16:04 UTC, nemesisdesign commented on README.rst
> +``openwisp_utils.utils.add_default_menu_items``
`add_default_menu_items` seems to not match the actual function name below

2020-10-26 16:04 UTC, nemesisdesign commented on openwisp_utils/utils.py
> +def add_menu_items(items, name_menu='OPENWISP_DEFAULT_ADMIN_MENU_ITEMS'):
what about `register_menu_items`? This is also consistent with similar functions we added in the monitoring and notifications modules.

2020-10-26 16:04 UTC, nemesisdesign commented on README.rst
> +    from openwisp_utils.utils import add_menu_items
would be good to suggest to use this in the `ready()` method of an `AppConfig` class.

2020-10-29 15:00 UTC, atb00ker commented
Updated this one! :smile:

2020-11-09 21:38 UTC, nemesisdesign approved these changes
Thanks @atb00ker :+1:!

2020-11-09 21:38 UTC, merged