0.7.4 release
openwisp/openwisp-utils pull request #181
Opened 2021-04-07 17:55 UTC by pandafy

Closes #179

2021-04-07 17:59 UTC, pandafy commented
`./run-qa-checks` and `./runtests.py` passed locally.

2021-04-08 02:25 UTC, nemesisdesign requested changes
Good, but this should not be merged (I think you may already know this). Only the changelog commit should be merged / cherry-picked to master once the release is done.

Please proceed to update the data as suggested below, then push a git signed tag and issue a signed release on pypi, I sent you an invite there and I'll make sure you have the permissions here on github.

2021-04-08 02:25 UTC, nemesisdesign commented on CHANGES.rst
> +Version 0.7.4 [2021-04-07]
let's update the date here to be the UTC time at the moment of release

2021-04-13 02:26 UTC, nemesisdesign approved these changes

2021-04-13 02:26 UTC, merged