[enhancement] Restyled filter design
openwisp/openwisp-utils pull request #214
Opened 2021-07-12 13:08 UTC by niteshsinha17

#### Changes

Created a new filter design. Now we can apply multiple filters at the same time.

#### Screenshots

![image](https://user-images.githubusercontent.com/42765292/125290226-b68aec00-e33d-11eb-9a74-4fa1f5ab4779.png)

#### Checklist

- [ ] I have read the [contributing guidelines](http://openwisp.io/docs/developer/contributing.html#how-to-commit-your-changes-properly).
- [x] I have manually tested the proposed changes.
- [x] I have written new test cases to avoid regressions. (if necessary)
- [x] I have updated the documentation. (e.g. README.rst)
- [x] I have added [change!] to commit title to indicate a backward incompatible change. (if required)
- [x] I have checked the links added / modified in the documentation.

Selenium testing will be the best for filters so I have not written any test for it here.

closes #196

2021-07-12 18:27 UTC, atb00ker reviewed
Huh? 25 commits to redesign the filters? :-/
I think it's dependent on the main menu PR, hence I see so many changes, ignoring the changes just looking at the filters, it looks good, I don't understand why the content of the dropdown comes bottom-to-top direction, usually, it's top-to-bottom direction; but still it looks good! :smile:

2021-07-16 15:30 UTC, niteshsinha17 commented
> Huh? 25 commits to redesign the filters? :-/
> I think it's dependent on the main menu PR, hence I see so many changes, ignoring the changes just looking at the filters, it looks good, I don't understand why the content of the dropdown comes bottom-to-top direction, usually, it's top-to-bottom direction; but still it looks good!

Yes, it is dependent on main menu PR. 
For the dropdown just keeping its animation similar to other dropdown on the page.

2021-08-01 17:37 UTC, nemesisdesign requested changes
Great work @niteshsinha17, I like it a lot! :+1: :+1: 

I pushed some minor improvements, please double check.

The only thing which does not convince me is the "apply filters" button, which when the filters aren't many and the screen is wide, doesn't work greatly.

But more importantly, it looks a bit bigger and the font is different than the other buttons below it, can you make sure the size and spacing is consistent?

![Screenshot from 2021-08-01 12-35-08](https://user-images.githubusercontent.com/841044/127780308-7929730e-7ae8-4a74-bc2b-3cb83dc02739.png)

2021-08-05 18:30 UTC, niteshsinha17 commented
>The only thing which does not convince me is the "apply filters" button, which when the filters aren't many and the screen is wide, doesn't work greatly.

We can switch back to normal working with no filter button when no of filters is less or equal to 3.

2021-08-07 01:01 UTC, nemesisdesign requested changes

2021-08-07 01:01 UTC, nemesisdesign commented on openwisp_utils/admin_theme/templatetags/ow_create_filter.py
> +    )
The coverage issue dropped, is it because of this file? Please ensure the coverage doesn't drop.

2021-08-09 00:58 UTC, nemesisdesign requested changes
Very good!
I took some time now to look at the code better and found some areas for improvement but mostly minor things :+1:.

2021-08-09 00:58 UTC, nemesisdesign commented on openwisp_utils/admin_theme/static/admin/css/ow-filters.css
> +  /* font-size: 14px; */
leftover here

2021-08-09 00:58 UTC, nemesisdesign commented on openwisp_utils/admin_theme/static/admin/js/ow-filter.js
> +function ButtonAnimation(button) {
why are you using uppercase first letter for a function?  Avoid this please, the convention is to use this for classes.

2021-08-09 00:58 UTC, nemesisdesign commented on openwisp_utils/admin_theme/static/admin/js/ow-filter.js
> +            return `${q}=${qs[q]}`;
indentation is odd here

2021-08-09 00:58 UTC, nemesisdesign commented on openwisp_utils/admin_theme/templates/admin/change_list.html
> +        <form id="changelist-form" method="post"{% if cl.formset and cl.formset.is_multipart %} enctype="multipart/form-data"{% endif %} novalidate>{% csrf_token %}
please try to break lines which are too long into multiple lines.

2021-08-09 00:58 UTC, nemesisdesign commented on openwisp_utils/admin_theme/templates/admin/filter.html
> +        <a href="{{ choice.query_string|iriencode }}" {% if choice.selected %} class="selected"{% endif %} title="{{ choice.display }}">
same here and above

2021-08-09 13:10 UTC, kkreitmair reviewed
@niteshsinha17 nice work again!

I found a browser support issue, but this is not a big thing to fix. :wink:

2021-08-09 14:08 UTC, niteshsinha17 commented
@nemesisdesign and @kkreitmair Fixed those minor issues

2021-08-10 00:34 UTC, nemesisdesign reviewed
While testing this in openwisp-controller, I have noticed there are different pages in which the apply filter button is not shown, is this fact dependent on how many filters are shown or how does it work exactly?

2021-08-10 00:57 UTC, niteshsinha17 commented
Filter button is shown when there is more than 4 filters otherwise it will work like filter works in django

2021-08-10 01:13 UTC, nemesisdesign requested changes
Ok @niteshsinha17 it looks good enough to me to be merged, I only see there's no information of this feature in the README and I think we should document it briefly (mention its existence with a dedicated section containing a screenshot) as well as explain things like the apply filter button being shown only when there are more than 4 filters.

2021-08-11 02:39 UTC, nemesisdesign requested changes

2021-08-11 02:39 UTC, nemesisdesign commented on README.rst
> +  :align: center
please push the gif to a `media` branch and load it from there so we avoid increasing the space required for downloading the main branch.

2021-08-11 17:55 UTC, nemesisdesign approved these changes
Great work :+1: :clap:

2021-08-11 17:56 UTC, merged