[test] Selenium test for filter #200
openwisp/openwisp-utils pull request #231
Opened 2021-08-10 07:14 UTC by niteshsinha17

#### Changes
Written selenium tests for the filter.

#### Checklist

- [x] I have read the [contributing guidelines](http://openwisp.io/docs/developer/contributing.html#how-to-commit-your-changes-properly).
- [x] I have manually tested the proposed changes.
- [x] I have written new test cases to avoid regressions. (if necessary)
- [x] I have updated the documentation. (e.g. README.rst)
- [x] I have added [change!] to commit title to indicate a backward incompatible change. (if required)
- [x] I have checked the links added / modified in the documentation.
close #200

2021-08-11 12:17 UTC, pniaps commented on openwisp_utils/admin_theme/templates/admin/base_site.html
> +    <link rel="icon" type="image/x-icon" href="{% static "ui/openwisp/images/favicon.png" %}" />
I've not tested locally, but **openwisp.css** and **favicon.png** are duplicated while testing?

2021-08-11 18:20 UTC, nemesisdesign reviewed
Please rebase on the latest master.

2021-08-11 20:09 UTC, atb00ker reviewed
This one has too many dependencies to be merged, I'll review this when those are merged! :smile:

2021-09-03 00:57 UTC, nemesisdesign requested changes
There's some conflicts with master. Could you fix those please?

2022-02-16 22:34 UTC, nemesisdesign approved these changes
Thanks :+1:

2022-02-16 22:34 UTC, merged