[enhancement] Added raw id filter #248
openwisp/openwisp-utils pull request #253
Opened 2021-09-14 13:31 UTC by niteshsinha17

This filter can be used in other modules to add a raw id filter
#### Checklist

- [x] I have read the [contributing guidelines](http://openwisp.io/docs/developer/contributing.html#how-to-commit-your-changes-properly).
- [x] I have manually tested the proposed changes.
- [ ] I have written new test cases to avoid regressions. (if necessary)
- [ ] I have updated the documentation. (e.g. README.rst)
- [ ] I have added [change!] to commit title to indicate a backward incompatible change. (if required)
- [ ] I have checked the links added / modified in the documentation.

closes #248

2021-09-15 14:44 UTC, nemesisdesign reviewed
@niteshsinha17 could you write a test that covers these 2 lines please?
https://coveralls.io/builds/42860654/source?filename=openwisp_utils%2Fadmin_theme%2Ffilter.py#L16
So we can avoid the build failure for coverage decreasing, albeit is small but it's nice to cover all new lines.

2021-09-15 17:05 UTC, pandafy requested changes
Good work @niteshsinha17 👍🏼 

I noticed some minor issues with code formatting. We can merge this one those are addressed.

2021-09-15 17:05 UTC, pandafy commented on openwisp_utils/admin_theme/static/admin/js/ow-filter.js
> +function initInputFilterHandler() {
This is great!

2021-09-15 17:12 UTC, nemesisdesign commented on openwisp_utils/admin_theme/static/admin/js/ow-filter.js
> +    });
don't we have style checks for JS code?

2021-09-23 05:00 UTC, niteshsinha17 commented on openwisp_utils/admin_theme/static/admin/js/ow-filter.js
> +    });
It checks on basic formatting.

2021-09-24 09:54 UTC, niteshsinha17 commented on openwisp_utils/admin_theme/static/admin/js/ow-filter.js
> +    // Create params 1map which knows about the last applied filters
Thanks

2021-09-24 15:26 UTC, nemesisdesign requested changes
Thanks @niteshsinha17 @pandafy!

See my comments below for some minor code improvements.

Definitely let's add a mention of this in the README, like at the end of this section: https://github.com/openwisp/openwisp-utils#admin-utilities, a screenshot in the media branch would be highly appreciated: https://github.com/openwisp/openwisp-utils/tree/media/docs.

2021-09-24 15:26 UTC, nemesisdesign commented on openwisp_utils/admin_theme/templates/admin/input_filter.html
> +      <input type="text" class="ow-input-filter-field" title="{{ spec.value | default_if_none:'' }}"value="{{ spec.value | default_if_none:'' }}"
a space is missing here before `value`.

I recommend breaking the attributes over new lines, eg:

```html
<input type="text"
       class="...."
       title="..."
       value="..."
/>
```

2021-09-24 15:26 UTC, nemesisdesign commented on openwisp_utils/admin_theme/templates/admin/input_filter.html
> +      <a class='field-clear' title="{% trans 'Clear' %}" href="{{ all_choice.query_string }}">&#x2716; </a>
same here, I would break this line

2021-10-05 13:11 UTC, niteshsinha17 commented on tests/test_project/admin.py
> +            return queryset.filter(name__icontains=self.value())
Yes need to be overridden,

2021-11-22 18:59 UTC, pandafy commented on openwisp_utils/admin_theme/templates/admin/input_filter.html
> +    <h3>{% blocktrans with filter_title=title %} By {{ filter_title }} {% endblocktrans %}</h3>
```suggestion
    <h3>{% blocktrans with filter_title=title %}By {{ filter_title }}{% endblocktrans %}</h3>
```

2021-11-29 16:11 UTC, nemesisdesign requested changes
I did some testing and looked at the code, it's good to merge except a few minor whitespace issues, see below.

2021-11-29 17:15 UTC, nemesisdesign approved these changes

2021-11-29 17:17 UTC, merged