Commit message bug fix : dot after the issue #187
openwisp/openwisp-utils pull request #256
Opened 2021-09-30 23:31 UTC by keshavgbpecdelhi

Issue : #187

#### Changes

> #Please explain changes made in your PR#

The problems like this https://github.com/openwisp/openwisp-controller/runs/2529479318 when placing a fullstop at the end of long description, is fixed. 

#### Checklist

- [ ] I have read the [contributing guidelines](http://openwisp.io/docs/developer/contributing.html#how-to-commit-your-changes-properly).
- [ ] I have manually tested the proposed changes.
- [ ] I have written new test cases to avoid regressions. (if necessary)
- [ ] I have updated the documentation. (e.g. README.rst)
- [ ] I have added [change!] to commit title to indicate a backward incompatible change. (if required)
- [ ] I have checked the links added / modified in the documentation.

> #Closes #(issue-number)#

2021-10-01 17:38 UTC, nemesisdesign requested changes
We need a failing test, then the patch should fix the failing test.

2021-10-02 04:27 UTC, keshavgbpecdelhi commented
Didn't get it 🤔

2021-10-03 05:16 UTC, codesankalp commented
@keshavgbpecdelhi You need to write a test that fails before your change and after introducing your change it passes.

See this:
https://github.com/openwisp/openwisp-utils/blob/9e182fd051e1b2142459014a9e5f6dc71a884ffa/tests/test_project/tests/test_qa.py#L137-L143

Add a test that fails when there is a dot in the commit message as mentioned in the issue and will pass if your changes are introduced in the code.

2021-10-05 15:57 UTC, nemesisdesign reviewed
> @keshavgbpecdelhi You need to write a test that fails before your change and after introducing your change it passes.
> 
> See this:
> 
> https://github.com/openwisp/openwisp-utils/blob/9e182fd051e1b2142459014a9e5f6dc71a884ffa/tests/test_project/tests/test_qa.py#L137-L143
> 
> Add a test that fails when there is a dot in the commit message as mentioned in the issue and will pass if your changes are introduced in the code.

Exactly, thank you @codesankalp.

2021-10-08 11:32 UTC, keshavgbpecdelhi commented
Sir if we remove the "." from long_desc like this :
long_desc = checked.split('.').join("");
And test cases making like this : 
[openwisp-utils/tests/test_project/tests/test_qa.py](url)
`@capture_stderr() 
 def test_qa_call_check_commit_message_failure(self): 
     options = [ 
         ['commitcheck'], 
         ['commitcheck', '--quiet', '--message', 'Hello World'], 
         ['commitcheck', '--quiet', '--message', '[qa] hello World'], 
         ['commitcheck', '--quiet', '--message', '[qa] Hello World.'],`
How do we check it and write like this. Here it's inside options and --quiet, --messages with [qa] not able to understand it. And how we arrange it.

2021-12-06 21:16 UTC, closed without merging

2021-12-06 21:19 UTC, devkapilbansal commented
Superseeded by #267