[feature] API docs theme #197
openwisp/openwisp-utils pull request #277
Opened 2022-01-27 10:55 UTC by Aryamanz29

Fixes #197

#### Changes

- Changed API docs theme to look similar to `admin`

#### Screenshots

![Screenshot from 2022-01-27 15-43-18](https://user-images.githubusercontent.com/56113566/151345215-7b1c0863-c54d-49fb-920f-e0719c2cafeb.png)

![Screenshot from 2022-01-27 16-10-54](https://user-images.githubusercontent.com/56113566/151345181-08916415-4601-4ae7-ae36-b9fa3d5b5c98.png)

#### Checklist

- [x] I have read the [contributing guidelines](http://openwisp.io/docs/developer/contributing.html#how-to-commit-your-changes-properly).
- [x] I have manually tested the proposed changes.
- [ ] I have written new test cases to avoid regressions. (if necessary)
- [ ] I have updated the documentation. (e.g. README.rst)
- [ ] I have added [change!] to commit title to indicate a backward incompatible change. (if required)
- [ ] I have checked the links added / modified in the documentation.

2022-01-28 22:09 UTC, Aryamanz29 commented
## `UPDATE :`

![Screenshot from 2022-01-29 02-50-58](https://user-images.githubusercontent.com/56113566/151628308-2cf218ec-56c1-463b-93ca-ce9e23bbd618.png)

![Screenshot from 2022-01-29 02-51-38](https://user-images.githubusercontent.com/56113566/151628310-e6bdb47c-d15b-4636-ba33-a2f5d3280f27.png)

2022-01-28 22:12 UTC, Aryamanz29 commented
@nemesisdesign  Do I have to make changes in `OP block` and `Models` CSS as well to look similar to **admin-theme**? 😅

![Screenshot from 2022-01-29 02-49-26](https://user-images.githubusercontent.com/56113566/151628454-d9c24c68-19da-4d12-9c30-cd64645e8804.png)

![Screenshot from 2022-01-29 02-49-37](https://user-images.githubusercontent.com/56113566/151628462-dcb68206-840c-4ede-a7b1-71733753e054.png)

2022-02-08 19:22 UTC, nemesisdesign commented
> @nemesisdesign Do I have to make changes in `OP block` styles as well to look similar to **admin-theme**? sweat_smile
> 
> ![Screenshot from 2022-01-29 03-44-55](https://user-images.githubusercontent.com/56113566/151629001-43f17478-a459-4e43-89e3-967a4742da34.png)

No this one let's not touch it.

2022-02-11 15:16 UTC, nemesisdesign requested changes
Thank you very much for your great work, is looking really good, let's make some more improvements!

### Swagger UI

Can you please make the authorize button look like:

![Screenshot from 2022-02-11 11-51-35](https://user-images.githubusercontent.com/841044/153613594-0ec2a603-db86-4fd2-8046-005d6581d82e.png)

Also, would be nice to switch the color of links (`<a>` elements) to the same color we use in the openwisp admin, making sure the links are not bold.

Take a look also at these buttons please (which do not look right):
![Screenshot from 2022-02-11 11-59-02](https://user-images.githubusercontent.com/841044/153614919-3a05c41a-9a46-4029-a63b-2a2243464b35.png)

### DRF browsable API

Here it is what I suggest:

- remove the gird background
- make the header background white
- make the logo and spacing around it similar to what's in the swagger API
- the labels of the form I would try to remove the bold and make it full black (`#000`)
- the tabs in the form, let's not make the background reddish but keep the background consistent with the rest of the form box, the background color on hover could be slightly lighter (eg: `#f9f9f9`)

2022-02-11 15:16 UTC, nemesisdesign commented on openwisp_utils/admin_theme/static/rest_framework/css/browsable-api.css
> +.navbar .nav li, .navbar .nav li a{
some improvements we tried:

```css
.navbar .nav li, .navbar .nav li a {
    margin-top: 20px;
    color: #000;
    background-color: rgba(0, 0, 0, 0.1);
    font-weight: bold;
    padding: 0.4em 0.9em 0.5em;
    text-align: center;
    border-radius: 0.25em;
}
```

2022-02-12 09:58 UTC, Aryamanz29 commented
### Swagger UI

- [x] ![Screenshot from 2022-02-11 11-51-35](https://user-images.githubusercontent.com/841044/153613594-0ec2a603-db86-4fd2-8046-005d6581d82e.png)

- [x] Also, would be nice to switch the color of links (`<a>` elements) to the same color we use in the openwisp admin, making sure the links are not bold.

####  NOW
![Screenshot from 2022-02-12 15-06-45](https://user-images.githubusercontent.com/56113566/153706421-44d064ae-ab59-43e6-b7a0-0582a174d3a6.png)

- [x] Take a look also at these buttons please (which do not look right): ![Screenshot from 2022-02-11 11-59-02](https://user-images.githubusercontent.com/841044/153614919-3a05c41a-9a46-4029-a63b-2a2243464b35.png)

#### NOW
![Screenshot from 2022-02-12 15-02-23](https://user-images.githubusercontent.com/56113566/153706455-c8b3930e-c947-4d35-9fe1-986fdc034105.png)

 
### DRF browsable API

- [x]  remove the gird background
- [x]  make the header background white
- [x]  make the logo and spacing around it similar to what's in the swagger API
- [x]  the labels of the form I would try to remove the bold and make it full black (`#000`)
- [x]  the tabs in the form, let's not make the background reddish but keep the background consistent with the rest of the form box, the background color on hover could be slightly lighter (eg: `#f9f9f9`)

### NOW

![Screenshot from 2022-02-12 15-09-12](https://user-images.githubusercontent.com/56113566/153706571-e93f9f4e-ad0a-41ca-b958-7336c7ff4027.png)

![Screenshot from 2022-02-12 15-09-23](https://user-images.githubusercontent.com/56113566/153706555-c7f829fe-1396-4d2d-889f-f09b2aeb5f73.png)

2022-02-12 14:25 UTC, nemesisdesign approved these changes
Thanks :+1:

2022-02-12 14:27 UTC, merged