[feature] Added custom celery task class #271
openwisp/openwisp-utils pull request #281
Opened 2022-02-14 16:48 UTC by pandafy

OpenwispCeleryTask class allows to set soft and hard time limits for
celery tasks using django settings.

Closes #271

#### Changes

> #Please explain changes made in your PR#

#### Screenshots

> #For UI changes, please share a screenshot#

#### Checklist

- [ ] I have read the [contributing guidelines](http://openwisp.io/docs/developer/contributing.html#how-to-commit-your-changes-properly).
- [ ] I have manually tested the proposed changes.
- [ ] I have written new test cases to avoid regressions. (if necessary)
- [ ] I have updated the documentation. (e.g. README.rst)
- [ ] I have added [change!] to commit title to indicate a backward incompatible change. (if required)
- [ ] I have checked the links added / modified in the documentation.

> #Closes #(issue-number)#

2022-02-14 17:52 UTC, pandafy commented on openwisp_utils/tasks.py
> +    time_limit = app_settings.CELERY_HARD_TIME_LIMIT
I wrote following tasks to test this 

```python
@shared_task(base=OpenwispCeleryTask)
def exceed_soft_time_limit():
    time.sleep(openwisp_utils_settings.CELERY_SOFT_TIME_LIMIT + 5)
```

And called it in following task

```python
def test_time_limits(self):
        tasks.exceed_soft_time_limit.delay()
        self.assertRaises(SoftTimeLimitExceeded, tasks.exceed_soft_time_limit.delay)
```

But the tests was not working even with eager mode.

2022-02-15 19:01 UTC, nemesisdesign requested changes

2022-02-15 19:01 UTC, nemesisdesign commented on README.rst
> +settings respectively.
let's make sure we explain that this task class should be used for regular background tasks but not for complex background tasks which can take a long time to execute (eg: firmware upgrades, network operations with retry mechanisms).

2022-02-15 19:01 UTC, nemesisdesign commented on README.rst
> +| default | ``30`` (in seconds) |
wouldn't these defaults prevent using this class in many tasks we have now scattered around OW?

I'd be more conservative and use 30 seconds and 60 seconds.

2022-02-15 19:13 UTC, nemesisdesign commented on README.rst
> +| default | ``30`` (in seconds) |
I think the hard time limit could even default to something higher, see https://github.com/openwisp/openwisp-notifications/pull/224#discussion_r807215214

2022-02-15 20:50 UTC, nemesisdesign reviewed
PS: I've done some manual testing and it seems to work :+1.
The weird thing is that I expected some output in the celery worker which told the task had hit the time limit but this isn't showing up not even in debug mode, but I have verified code after the sleep is not executed.

2022-02-16 22:29 UTC, nemesisdesign approved these changes

2022-02-16 22:32 UTC, nemesisdesign approved these changes

2022-02-16 22:33 UTC, merged