[chores] Upgrade drf-yasg~=1.21.0 #306
openwisp/openwisp-utils pull request #317
Opened 2022-10-03 17:39 UTC by sassy-bugs

Removed the workaround for DRF-yasg as described in #306 .

#### Changes

> Removed the following workaround added in static file storage

[openwisp-utils/openwisp_utils/storage.py](https://github.com/openwisp/openwisp-utils/blob/afa8f7bfa7a4532aab7c1c4fa4d76e55eea635c7/openwisp_utils/storage.py#L10-L23)

#### Screenshots

> #For UI changes, please share a screenshot#

#### Checklist

- [x] I have read the [contributing guidelines](http://openwisp.io/docs/developer/contributing.html#how-to-commit-your-changes-properly).
- [x] I have manually tested the proposed changes.
- [ ] I have written new test cases to avoid regressions. (if necessary)
- [ ] I have updated the documentation. (e.g. README.rst)
- [ ] I have added [change!] to commit title to indicate a backward incompatible change. (if required)
- [ ] I have checked the links added / modified in the documentation.

> #Closes #306 #

2022-10-04 09:49 UTC, nemesisdesign requested changes
I guess this will have to be updated too:
https://github.com/openwisp/openwisp-utils/blob/master/setup.py#L61

2022-10-04 10:28 UTC, sassy-bugs commented
In my recent commit I have upgraded drf-yasg as described in the issue #306 I believe this commit will resolve this issue completely.

2022-10-04 16:16 UTC, nemesisdesign commented
@sassy-bugs QA checks failing

2022-10-07 14:33 UTC, nemesisdesign commented
@sassy-bugs please try doing `git rebase -i HEAD~2` then squash the second commit, it will let you edit the commit message, you can use:

```
[chores] Upgrade drf-yasg~=1.21.0 #306

Removed the workaround for DRF-yasg.
Closes #306
```

2022-10-14 14:16 UTC, nemesisdesign commented
@sassy-bugs ping

2022-10-15 08:59 UTC, sassy-bugs commented
I'm sorry I have not been feeling well lately. Will follow
your instructionsand do the needful by today.
Thank you for being so patient with me
Regards,
Agrima

On Fri, 14 Oct, 2022, 7:46 pm Federico Capoano, ***@***.***>
wrote:

> @sassy-bugs <https://github.com/sassy-bugs> ping
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openwisp/openwisp-utils/pull/317#issuecomment-1279069695>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXG6US4AYIEBWXG5JPBG7ITWDFTLXANCNFSM6AAAAAAQ3Z4ALU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-18 12:21 UTC, nemesisdesign commented
@sassy-bugs ping

2022-12-20 11:21 UTC, Aryamanz29 commented
@nemesisdesign I have rebased this branch and fixed the CI build.

2022-12-20 21:12 UTC, nemesisdesign approved these changes

2022-12-20 21:12 UTC, merged