[ci] Added GitHub workflow to replicate commits to version branch
openwisp/openwisp-utils pull request #423
Opened 2024-12-18 10:09 UTC by pandafy

## Checklist

- [x] I have read the [OpenWISP Contributing Guidelines](http://openwisp.io/docs/developer/contributing.html).
- [x] I have manually tested the changes proposed in this pull request.
- [ ] I have written new test cases for new code and/or updated existing tests for changes to existing code.
- [ ] I have updated the documentation.

2024-12-18 12:06 UTC, pandafy commented
I have tested the GitHub action on my fork: 

- [Creating a new branch from the version number](https://github.com/pandafy/openwisp-utils/actions/runs/12392581882) 
- [Replicating the master branch](https://github.com/pandafy/openwisp-utils/actions/runs/12392528667)

2024-12-18 15:12 UTC, nemesifier requested changes
Is there a way to create a reusable github action so we don't need to duplicate this in each repo? That would allow us to change this for all repos from a single place.

2024-12-18 15:12 UTC, nemesifier commented on .github/workflows/version-branch.yml
> +        print(f"{VERSION[0]}.{VERSION[1]}.x")
Wouldn't this produce something like `1.2.x`? We are using branch names without the x now.

2024-12-18 15:12 UTC, nemesifier commented on .github/workflows/version-branch.yml
> +        git push origin $VERSION
What happens here if we ever need to push force on master?

2024-12-18 15:12 UTC, nemesifier commented on openwisp_utils/__init__.py
> +VERSION = (1, 2, 1, 'alpha')
why 1.2.1?

2024-12-18 15:30 UTC, pandafy commented
> Is there a way to create a reusable github action so we don't need to duplicate this in each repo? That would allow us to change this for all repos from a single place.

We will need to find a way to automatically get the module name. Maybe, we can set this as an input parameter in GitHub workflow.

2024-12-19 13:49 UTC, nemesifier approved these changes

2024-12-19 13:51 UTC, merged